### ISSUE TITLE
Issue with the new version 

### ISSUE THREAD

**Issue by meerasebastian21** [ljharb/define-properties#35]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for define-properties@^1.2.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by ljharb** [comment]
Sounds like you may be using a private registry that isn’t configured properly?

**Comment by meerasebastian21** [comment]
Yes, we are using a private repository. This issue suddenly arose just one day ago. I believe the problem may be related to the recent update to version v1.2.1, which occurred two days ago, as we haven't made any changes to the code.

**Comment by ljharb** [comment]
Then your private registry needs to be fixed so it installs from the public registry properly - since v1.2.1 is quite published https://www.npmjs.com/package/define-properties
