### ISSUE TITLE
Can't install define-properties@^1.2.1.

### ISSUE THREAD

**Issue by iikel1** [ljharb/define-properties#36]
I am trying to install next js project which required define-properties@^1.2.1.

I got this error 
`
pm ERR! code ETARGET
npm ERR! notarget No matching version found for define-properties@^1.2.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
`

I have tried to `npm view define-properties versions` and I got this 
`[
  '1.0.0', '1.0.1',
  '1.0.2', '1.1.0',
  '1.1.1', '1.1.2',
  '1.1.3', '1.1.4',
  '1.2.0'
]`

**Comment by ljharb** [comment]
I get
```
[
  '1.0.0', '1.0.1',
  '1.0.2', '1.1.0',
  '1.1.1', '1.1.2',
  '1.1.3', '1.1.4',
  '1.2.0', '1.2.1'
]
```

which suggests that `npm config get registry` won't be the public one, and whatever registry you're using isn't keeping itself up to date properly.

**Comment by ljharb** [comment]
In particular, that version was published on September 13th.
